### ISSUE TITLE
traceback (requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.skilledtests.com', port=80): Max retries exceeded with url: /wiki/index.php5 (Caused by <class 'httplib.BadStatusLine'>: ''))

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [WikiTeam/wikiteam#158]
I was doing this (1)

and then dumpgenerator.py crashed (see below).

more details at: (2)

versions used:
Python 2.7.6
DumpGenerator 0.3.0-alpha
mediawiki 1.19.17

(1) https://github.com/WikiTeam/wikiteam/issues/26#issuecomment-48753616
(2) http://www.skilledtests.com/wiki/DumpGenerator#traceback_nr._2

Downloaded 790 pages
    Category:Canada, 1 edit
    Category:Canadian, 1 edit
    Category:Cat, 1 edit
    Category:Cello, 1 edit
    Category:Chaos theory, 1 edit
Traceback (most recent call last):
  File "dumpgenerator.py", line 1503, in <module>
    main()
  File "dumpgenerator.py", line 1495, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1241, in createNewDump
    generateXMLDump(config=config, titles=titles, session=other['session'])
  File "dumpgenerator.py", line 579, in generateXMLDump
    xml = getXMLPage(config=config, title=title, session=session)
  File "dumpgenerator.py", line 465, in getXMLPage
    xml = getXMLPageCore(params=params, config=config, session=session)
  File "dumpgenerator.py", line 435, in getXMLPageCore
    r = session.post(url=config['index'], data=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 498, in post
    return self.request('POST', url, data=data, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.skilledtests.com', port=80): Max retries exceeded with url: /wiki/index.php5 (Caused by < class 'httplib.BadStatusLine' >: '')

**Comment by nemobis** [comment]
The wiki is now dead and redirects to a spam domain, but we did manage to get dumps in 2014 and 2017:
https://archive.org/details/wiki-skilledtestscom_wiki
https://archive.org/details/Wiki-IAskQuestions
