### ISSUE TITLE
Update editthis.info wikis list

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#165]
I'm done downloading 1306 EditThis wikis. If the list gets updated, I can dump any new wiki as well. One never knows how much time is left before it goes down.

**Comment by Hydriz** [comment]
Is there any way to obtain a list of wikis on this wikifarm?

**Comment by nemobis** [comment]
Hydriz Scholz, 07/08/2015 08:10:
> Is there any way to obtain a list of wikis on this wikifarm?

Not that I know.

**Comment by Gantron1** [comment]
@nemobis, How were you able to archive EditThis.info wikis? I tried with both api and index methods, but both quit with an error. 

Output from api method:
```
$ python dumpgenerator.py --api=http://editthis.info/create_your_own_story/api.php --xml --images
Checking API... http://editthis.info/create_your_own_story/api.php
MediaWiki API seems to work but returned no index URL
API is OK: http://editthis.info/create_your_own_story/api.php
Checking index.php... http://editthis.info/create_your_own_story/index.php
Looks like the page called Index.php, not index.php itself
Traceback (most recent call last):
  File "dumpgenerator.py", line 2080, in <module>
    main()
  File "dumpgenerator.py", line 2028, in main
    config, other = getParameters(params=params)
  File "dumpgenerator.py", line 1427, in getParameters
    index = '/'.join(index.split('/')[:-1])
AttributeError: 'NoneType' object has no attribute 'split'
```

Output from index method:
```
$ python dumpgenerator.py --index=http://editthis.info/create_your_own_story/ --xml --images
API not available. Trying with index.php only.
Checking index.php... http://editthis.info/create_your_own_story/
index.php is OK
#########################################################################
# Welcome to DumpGenerator 0.3.0-alpha by WikiTeam (GPL v3)                   #
# More info at: https://github.com/WikiTeam/wikiteam                    #
#########################################################################

#########################################################################
# Copyright (C) 2011-2014 WikiTeam                                      #
# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

Analysing http://editthis.info/create_your_own_story/
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
16 namespaces found
    Retrieving titles in the namespace 0
Uncached page load rate limit reached -> 2 per second. 
This wiki doesn't use marks to split

```

**Comment by nemobis** [comment]
Gantron1, 22/08/2016 04:36:
> @nemobis <https://github.com/nemobis>, How were you able to archive
> EditThis.info wikis? I tried with both api and index methods, but both
> quit with an error.

All I know is documented at http://archiveteam.org/index.php?title=EditThis

**Comment by emijrp** [comment]
EditThis is down for some days, by the way.

2016-09-21 8:44 GMT+02:00 nemobis <notifications@github.com>:

**Comment by Gantron1** [comment]
Thankfully, it's back up now, but for awhile there, I thought the site was a victim of the exact reason for this WikiTeam project.

@nemobis 's url says to do the following: 

- add --exnamespaces=8,9
- use API and a --delay=60

I did so, but it still didn't work:

> $ python dumpgenerator.py --api=http://editthis.info/create_your_own_story/api.php --xml --images --exnamespaces=8,9 --delay=60
> Checking API... http://editthis.info/create_your_own_story/api.php
> MediaWiki API seems to work but returned no index URL
> API is OK: http://editthis.info/create_your_own_story/api.php
> Checking index.php... http://editthis.info/create_your_own_story/index.php
> Looks like the page called Index.php, not index.php itself
> Traceback (most recent call last):
>   File "dumpgenerator.py", line 2083, in <module>
>     main()
>   File "dumpgenerator.py", line 2031, in main
>     config, other = getParameters(params=params)
>   File "dumpgenerator.py", line 1430, in getParameters
>     index = '/'.join(index.split('/')[:-1])
> AttributeError: 'NoneType' object has no attribute 'split'

This is the same error as before, just the line numbers are different because I upgraded to the latest dumpgenerator.py.

**Comment by nemobis** [comment]
Gantron1, 23/09/2016 19:26:
> I did so, but it still didn't work:

If you were blacklisted, you'll have to wait quite a while until the ban 
expires. Do you manage to open any editthis URL from your IP?

**Comment by emijrp** [comment]
2016-09-23 19:26 GMT+02:00 Gantron1 <notifications@github.com>:

> $ python dumpgenerator.py --api=http://editthis.info/
> create_your_own_story/api.php --xml --images --exnamespaces=8,9 --delay=60
>
>
Try adding too --index=urltoindex

I think the script assumes it is http://editthis.info/create_
your_own_story/index.php but it is wrong. Maybe just
http://editthis.info/create_your_own_story/ ?
<http://editthis.info/create_your_own_story/index.php>

**Comment by nemobis** [comment]
By the way I add some of these downloads running for years on my server, but at some point I forgot to keep restarting them.
