### ISSUE TITLE
Download history of multiple pages at once

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#18]
_From [nemow...@gmail.com](https://code.google.com/u/101255742639286016490/) on July 09, 2011 17:50:35_

I don't understand the code much so excuse me if I say silly things.
The script currently seems to download the history of a single page at once. To reduce the number of requests and making things faster, it would probably be better if it could ask the API for the history of multiple titles at once, after checking this won't cross the revisions limit.

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=18_

**Comment by Betacommand** [comment]
Any update on this? It would be really useful with the --curonly option too. Right now its a 1:1 load for the servers while it could easily be less.

**Comment by nemobis** [comment]
This is already fixed, just use --xmlrevisions.

**Comment by nemobis** [comment]
Example failure on MediaWiki 1.15:
```
http://www.metsapirtti.net/wiki/api.php
Getting the XML header from the API
Retrieving the XML for every page from the beginning
Sleeping... 1 seconds...
16 namespaces found
Trying to export all revisions from namespace 0
Warning. Could not use allrevisions, wiki too old.
/home/users/federico/.local/lib/python2.7/site-packages/wikitools/api.py:155: FutureWarning: The querycontinue option is deprecated and will be removed
in a future release, use the new queryGen function instead
for queries requring multiple requests
  for queries requring multiple requests""", FutureWarning)
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2323, in <module>
    main()
  File "./dumpgenerator.py", line 2315, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1882, in createNewDump
    generateXMLDump(config=config, titles=titles, session=other['session'])
  File "./dumpgenerator.py", line 745, in generateXMLDump
    for xml in getXMLRevisions(config=config, session=session):
  File "./dumpgenerator.py", line 872, in getXMLRevisions
    results = prequest.query()
  File "/home/users/federico/.local/lib/python2.7/site-packages/wikitools/api.py", line 165, in query
    raise APIError(data['error']['code'], data['error']['info'])
wikitools.api.APIError: (u'internal_api_error_MWException', u'Exception Caught: Internal error in ApiResult::setElement: Attempting to add element revisions=50, existing value is 500')
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```
