### ISSUE TITLE
Catch requests.exceptions.ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#247]
This should probably not be a fatal:
```
    return self.request('POST', url, data=data, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='gluecksspiel.guru', port=80): Max retries exceeded with url: /api.php (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python2.7/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python2.7/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python2.7/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Opening configuration file /etc/apt/apt.conf.d/15pax-mark - ifstream::ifstream (13: Permission denied)

Original exception was:
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2031, in <module>
    main()
  File "./dumpgenerator.py", line 1979, in main
    config, other = getParameters(params=params)
  File "./dumpgenerator.py", line 1355, in getParameters
    check = checkAPI(api=api, session=session)
  File "./dumpgenerator.py", line 1470, in checkAPI
    'format': 'json'}
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 498, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='gluecksspiel.guru', port=80): Max retries exceeded with url: /api.php (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
#########################################################################
```

**Comment by nemobis** [comment]
Also
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python2.7/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python2.7/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python2.7/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Opening configuration file /etc/apt/apt.conf.d/15pax-mark - ifstream::ifstream (13: Permission denied)

Original exception was:
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2031, in <module>
    main()
  File "./dumpgenerator.py", line 1979, in main
    config, other = getParameters(params=params)
  File "./dumpgenerator.py", line 1355, in getParameters
    check = checkAPI(api=api, session=session)
  File "./dumpgenerator.py", line 1470, in checkAPI
    'format': 'json'}
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 498, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/users/federico/.local/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```
