### ISSUE TITLE
dumpgenerator.py fails to dump files if a video embedded with the YouTube plugin is within.

### ISSUE THREAD

**Issue by wertercatt** [WikiTeam/wikiteam#283]
The YouTube Mediawiki plugin embeds YouTube videos as pages within the "File:" namespace. As these are links to offsite videos and not a file, when dumpgenerator.py attempts to download them, it fails. This results in it immediately erroring and stopping, preventing any files after the video from being downloaded. More preferable behavior would be having dumpgenerator.py list files it fails to download in errors.log, and continue its downloading of the other files. Please see [this page](http://bootleggames.wikia.com/wiki/File:Mario_%22Cart%22_Famiclon_Edition) as an example of the kind of page that causes dumpgenerator.py to error out. The traceback is as follows:

```
Traceback (most recent call last):
  File "dumpgenerator.py", line 2084, in <module>
    main()
  File "dumpgenerator.py", line 2076, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1663, in createNewDump
    session=other['session'])
  File "dumpgenerator.py", line 1108, in generateImageDump
    imagefile = open(filename3, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'./bootleggameswikiacom-20
161018-wikidump/images/Mario "Cart" Famiclon Edition'
```

**Comment by wertercatt** [comment]
Actually, looking at the traceback, it appears my issue is due to the fact that `"` symbols are not allowed in Windows filenames. Closing this issue.
