### ISSUE TITLE
Does not work with http://mgewiki.com/

### ISSUE THREAD

**Issue by nonamethanks** [WikiTeam/wikiteam#294]
```
[ ]----> python dumpgenerator.py http://mgewiki.com/ --images 
Checking API... http://mgewiki.com/api.php
API is OK: http://mgewiki.com/api.php
Checking index.php... http://mgewiki.com/index.php
index.php is OK

Analysing http://mgewiki.com/api.php
Trying generating a new dump into a new directory...
Retrieving image filenames
.............    Found 6377 images
6377 image names loaded
Image filenames and URLs saved at... mgewikicom-20170515-images.txt
Retrieving images from "start"
Creating "./mgewikicom-20170515-wikidump/images" directory
    In attempt 1, XML for "Image:-Basilisk19.jpg" is wrong. Waiting 20 seconds and reloading...
    In attempt 2, XML for "Image:-Basilisk19.jpg" is wrong. Waiting 40 seconds and reloading...
    In attempt 3, XML for "Image:-Basilisk19.jpg" is wrong. Waiting 60 seconds and reloading...
    In attempt 4, XML for "Image:-Basilisk19.jpg" is wrong. Waiting 80 seconds and reloading...
    We have retried 5 times
    MediaWiki error for "Image:-Basilisk19.jpg", network error or whatever...
    Saving in the errors log, and skipping...
Traceback (most recent call last):
  File "dumpgenerator.py", line 2084, in <module>
    main()
  File "dumpgenerator.py", line 2076, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1663, in createNewDump
    session=other['session'])
  File "dumpgenerator.py", line 1118, in generateImageDump
    session=session)  # use Image: for backwards compatibility
  File "dumpgenerator.py", line 478, in getXMLFileDesc
    return("".join([x for x in getXMLPage( config=config, title=title, verbose=False, session=session)]))
  File "dumpgenerator.py", line 589, in getXMLPage
    xml = getXMLPageCore(params=params, config=config, session=session)
  File "dumpgenerator.py", line 549, in getXMLPageCore
    raise ExportAbortedError(config['index'])
__main__.ExportAbortedError: Export from 'http://mgewiki.com/index.php' did not return anything.


```

It similarly fails with the --xml switch, with
```
Retrieving the XML for every page from "start"
    In attempt 1, XML for "Main_Page" is wrong. Waiting 20 seconds and reloading...

```

**Comment by nonamethanks** [comment]
Err... Did I do something wrong? The issue with said wiki exists.

**Comment by nemobis** [comment]
My message got lost somewhere:
> This is expected, the wiki requires login for Special:Export.
> http://mgewiki.com/w/Special:Export/Main_Page

**Comment by nonamethanks** [comment]
Ah. I see, thanks for the explanation.
