### ISSUE TITLE
Private wikis: catch KeyError: 'query' in checkAPI

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#304]
This wiki requires login, we should recognise it and exit cleanly (maybe also save the main page's HTML or something):
```
#########################################################################
# Downloading http://aliencity.org/w/api.php      
#########################################################################
Checking API... http://aliencity.org/w/api.php
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2107, in <module>
    main()
  File "./dumpgenerator.py", line 2055, in main
    config, other = getParameters(params=params)
  File "./dumpgenerator.py", line 1414, in getParameters
    check = checkAPI(api=api, session=session)
  File "./dumpgenerator.py", line 1552, in checkAPI
    if result['query']:
KeyError: 'query'
```
```
{
    "error": {
        "code": "readapidenied",
        "info": "You need read permission to use this module",
        "*": "See http://aliencity.org/w/api.php for API usage"
    }
}
```

**Comment by nemobis** [comment]
For now I've just changed `if result['query']:' to `if result:` in my local version.
```
Checking API... http://www.soest.hawaii.edu/wiki/api.php
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2107, in <module>
    main()
  File "./dumpgenerator.py", line 2055, in main
    config, other = getParameters(params=params)
  File "./dumpgenerator.py", line 1414, in getParameters
    check = checkAPI(api=api, session=session)
  File "./dumpgenerator.py", line 1552, in checkAPI
    if result['query']:
KeyError: 'query'
```

**Comment by nemobis** [comment]
Probably this is the same root reason, https://lsj.translatum.gr/wiki/special:statistics says restricted to editor group. I see a loop:

```

Analysing https://lsj.translatum.gr/w/api.php
Loading config file...
Resuming previous dump process...
Title list is incomplete. Reloading...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
28 namespaces found
    Retrieving titles in the namespace 0
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```
