### ISSUE TITLE
wikia.py: skip closed wikis

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#316]
https://f909-photo.wikia.com/api.php  says "Closed wiki" and it's an HTTP 410.

Seen in launcher.py as:
```
Analysing https://f909-photo.wikia.com/api.php
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2291, in <module>
    main()
  File "./dumpgenerator.py", line 2283, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1847, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "./dumpgenerator.py", line 416, in getPageTitles
    for title in titles:
  File "./dumpgenerator.py", line 245, in getPageTitlesAPI
    config=config, session=session)
  File "./dumpgenerator.py", line 216, in getNamespacesAPI
    for i in result['query']['namespaces'].keys():
KeyError: 'query'
tail: cannot open 'f909_photowikiacom-20180520-wikidump/f909_photowikiacom-20180520-history.xml' for reading: No such file or directory
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
The list of active wikis changes quickly, I was probably just using an old list.
