### ISSUE TITLE
dumpgenerator.py cancels gigabytes of dumping after only 10 seconds of net lag

### ISSUE THREAD

**Issue by Wikiteam-on-Windows** [WikiTeam/wikiteam#338]
Corruption could be less likely to happen if there was more than a 10 second timeout on downloading pages before stopping an hours-long download just because of less than a minute of lag (when Archive Team are forced to use proxies due to blocking waiting for these kind of lag spikes to end can be commonplace too), maybe it should retry a few times before giving up (such as dumpgenerator.py does with the very first attempt to grab the page list)

And even then, maybe leave it to the user to choose continue or cancel, as it's quite possible when the connection problems are gone or proxy adjusted the downloading can continue uninterrupted and no real reason to write off hours of work (given how manually restarting with --resume can introduce corruption)

These are errors I have seen while dumping:

FIRST EVER DUMP ERROR:
```python
Downloaded <THOUSANDS> pages
    File:<FILENAME>.jpg, 1 edit
    File:<FILENAME>.jpg, 2 edits
Traceback (most recent call last):
  File "dumpgenerator.py", line 2323, in <module>
    main()
  File "dumpgenerator.py", line 2315, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1882, in createNewDump
    generateXMLDump(config=config, titles=titles, session=other['session'])
  File "dumpgenerator.py", line 780, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "dumpgenerator.py", line 668, in getXMLPage
    params=params, config=config, session=session)
  File "dumpgenerator.py", line 603, in getXMLPageCore
    r = session.post(url=config['index'], params=params, headers=headers, timeout=10)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='<HOSTNAME>', port=443): Read timed out. (read timeout=10)
```

SECOND DUMP ERROR DURING THE SAME DUMP AS PREVIOUS PASTE ABOVE, AFTER USING --resume --path=<PATHNAMEHERE> (only lines 8 through 11 below are different from the previous error above):
```python
Downloaded <THOUSANDS> pages
    File:<FILENAME>.jpg, 2 edits
    File:<FILENAME>.jpg, 4 edits
Traceback (most recent call last):
  File "dumpgenerator.py", line 2323, in <module>
    main()
  File "dumpgenerator.py", line 2315, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 1882, in resumePreviousDump
    session=other['session'])
  File "dumpgenerator.py", line 780, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "dumpgenerator.py", line 668, in getXMLPage
    params=params, config=config, session=session)
  File "dumpgenerator.py", line 603, in getXMLPageCore
    r = session.post(url=config['index'], params=params, headers=headers, timeout=10)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='<HOSTNAME>', port=443): Read timed out. (read timeout=10)
```

For a different dump, which failed after some lag while downloading images instead of the XML (many lines different in the error this time):
```python
    Downloaded <THOUSANDS> images
    Downloaded <THOUSANDS> images
Traceback (most recent call last):
  File "dumpgenerator.py", line 2323, in <module>
    main()
  File "dumpgenerator.py", line 2315, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1894, in createNewDump
    session=other['session'])
  File "dumpgenerator.py", line 1313, in generateImageDump
    session=session)  # use Image: for backwards compatibility
  File "dumpgenerator.py", line 525, in getXMLFileDesc
    return("".join([x for x in getXMLPage( config=config, title=title, verbose=False, session=session)]))
  File "dumpgenerator.py", line 639, in getXMLPage
    xml = getXMLPageCore(params=params, config=config, session=session)
  File "dumpgenerator.py", line 603, in getXMLPageCore
    r = session.post(url=config['index'], params=params, headers=headers, timeout=10)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='<HOSTNAME>', port=443): Read timed out. (read timeout=10)
```

A while after resuming the same dump as the above code copypaste (only lines 6 through 8 different from the above one):
```python
    Downloaded <THOUSANDS> images
    Downloaded <THOUSANDS> images
Traceback (most recent call last):
  File "dumpgenerator.py", line 2323, in <module>
    main()
  File "dumpgenerator.py", line 2313, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 2030, in resumePreviousDump
    session=other['session'])
  File "dumpgenerator.py", line 1313, in generateImageDump
    session=session)  # use Image: for backwards compatibility
  File "dumpgenerator.py", line 525, in getXMLFileDesc
    return("".join([x for x in getXMLPage( config=config, title=title, verbose=False, session=session)]))
  File "dumpgenerator.py", line 639, in getXMLPage
    xml = getXMLPageCore(params=params, config=config, session=session)
  File "dumpgenerator.py", line 603, in getXMLPageCore
    r = session.post(url=config['index'], params=params, headers=headers, timeout=10)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/<USERNAME>/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='<HOSTNAME>', port=443): Read timed out. (read timeout=10)
```

NOTE: I had to write out these errors painstakingly by hand, as well as introducing a risk of human error for people reporting issues, it may cause an aversion to making the effort in a lot of people that might cause things to go unreported, having all output the script makes be logged into a text file would be a good idea maybe (and also add another form of passive check that it's legit for people looking over archives other people have made)

**Comment by WAUthethird** [comment]
You couldn't have copied the output of your command line by selecting and right-clicking? I assume you're using Windows, yes? It's not impossible.

**Comment by nemobis** [comment]
Thank you for downloading wikis and for reporting the issues you encountered. Please file more specific issues.

1) It's already possible to use the `--delay` option. It's possible that some timeouts are hardcoded; if some of them are problematic, please file an issue about that.
2) If dumpgenerator.py deleted some files without prompting, I believe that would be a bug. It's not clear to me whether that happend.
3) If you asked launcher.py or dumpgenerator.py to redo or resume the bug and part or all of the XML was thrown away, that's expected. The script values accuracy over speed, and it's not always possible to artificially reconstruct valid XML dumps. If you don't want to lose your XML files, make a copy of them before asking dumpgenerator/launcher.py to modify them.

Thank you.
