### ISSUE TITLE
Handle HTTP 406 on lackadaisycats.com

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#347]
```
Analysing http://lackadaisycats.com/wiki/api.php
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
Sleeping... 1 seconds...
Error: could not get namespaces from the API request
HTTP 406
<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Sec
urity.</p></body></html>
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2323, in <module>
    main()
  File "./dumpgenerator.py", line 2315, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1880, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "./dumpgenerator.py", line 429, in getPageTitles
    for title in titles:
  File "./dumpgenerator.py", line 252, in getPageTitlesAPI
    config=config, session=session)
TypeError: 'NoneType' object is not iterable
tail: cannot open 'lackadaisycatscom_wiki-20200208-wikidump/lackadaisycatscom_wiki-20200208-history.xml' for reading: No such file or directory
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
Looks like the API returns junk when requests come from a non-browser user-agent...
