### ISSUE TITLE
MediaWiki 1.15 or 1.16 fails with TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#348]
Current master, normal --xml --api:
```
Analysing http://wiki.apnchanger.org/index.php
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
Sleeping... 1 seconds...
Error: could not get namespaces from the API request
...
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2328, in <module>
    main()
  File "./dumpgenerator.py", line 2320, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1885, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "./dumpgenerator.py", line 429, in getPageTitles
    for title in titles:
  File "./dumpgenerator.py", line 252, in getPageTitlesAPI
    config=config, session=session)
TypeError: 'NoneType' object is not iterable
tail: cannot open 'wikiapnchangerorg-20200208-wikidump/wikiapnchangerorg-20200208-history.xml' for reading: No such file or directory
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```
```

**Comment by nemobis** [comment]
Same with MediaWiki 1.15 https://wiki.foppa.dk/index.php/Main_Page

```
API not available. Trying with index.php only.
Checking index.php... http://wiki.foppa.dk/index.php
index.php is OK
...
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2328, in <module>
    main()
  File "./dumpgenerator.py", line 2320, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1885, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "./dumpgenerator.py", line 429, in getPageTitles
    for title in titles:
  File "./dumpgenerator.py", line 252, in getPageTitlesAPI
    config=config, session=session)
TypeError: 'NoneType' object is not iterable
tail: cannot open 'wikifoppadk-20200208-wikidump/wikifoppadk-20200208-history.xml' for reading: No such file or directory
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```
https://wiki.foppa.dk/api.php?action=query&meta=siteinfo&siprop=namespaces&format=json seems ok and seems to work in  3d04dcbf5c24db1ae54f7cb3e4ec512444e6e28d

**Comment by nemobis** [comment]
Still happens after that commit on some wiki (1.16.5), seems to work locally though:
```
Analysing http://www.dharmakaya.ru/mediawiki/index.php
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
Sleeping... 1 seconds...
Error: could not get namespaces from the API request
HTTP 200                                        
...
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2323, in <module>
    main()
  File "./dumpgenerator.py", line 2315, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1880, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "./dumpgenerator.py", line 429, in getPageTitles
    for title in titles:
  File "./dumpgenerator.py", line 252, in getPageTitlesAPI
    config=config, session=session)
TypeError: 'NoneType' object is not iterable
tail: cannot open 'dharmakayaru_mediawiki-20200208-wikidump/dharmakayaru_mediawiki-20200208-history.xml' for reading: No such file or directory
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
If there's no namespace to ask for we can't do much, but we can avoid the specific error.
