### ISSUE TITLE
xmswiki.com connection refused

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#350]
Let's see if this is temporary

```
Downloaded 190 pages
ATTENTION: This wiki does not allow some parameters in Special:Export, therefore pages with large histories may be truncated
    CityWater Tutorial Links, 1 edit
Sleeping... 1 seconds...
ATTENTION: This wiki does not allow some parameters in Special:Export, therefore pages with large histories may be truncated
    CityWater Tutorials, 1 edit
Sleeping... 1 seconds...
    Connection error: HTTPConnectionPool(host='www.xmswiki.com', port=80): Max retries exceeded with url: /index.php?action=submit&offset=1&limit=1000&pages=CityWater_User%27s_Manual&title=Special%3AExport (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x68dddf74c090>: Failed to establish a new connection: [Errno 111] Connection refused',))
    In attempt 1, XML for "CityWater_User's_Manual" is wrong. Waiting 20 seconds and reloading...
```

**Comment by nemobis** [comment]
That particular run failed, but it seems to complete just fine with `--xmlrevisions` at least.

**Comment by nemobis** [comment]
Curiously it has failed when downloading the main page:
```
1 more revisions exported
XML dump saved at... xmswikicom-20200210-history.xml
Downloading index.php (Main Page) as index.html
Traceback (most recent call last):
  File "dumpgenerator.py", line 2439, in <module>

  File "dumpgenerator.py", line 2433, in main
    saveConfig(config=config, configfilename=configfilename)
  File "dumpgenerator.py", line 2176, in saveIndexPHP
    def saveIndexPHP(config={}, session=None):
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 529, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 533, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 239, in _get_conn
    conn.close()
  File "/usr/lib64/python2.7/httplib.py", line 841, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 230, in close
    return self.connection.shutdown()
OpenSSL.SSL.Error: []
```

This seems to come and go, both with GET and POST.
