### ISSUE TITLE
Wikia zh wiki: PageMissingError: page 'En:' not found

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#361]
Maybe some weirdness with interwikis?

```
https://battlefordreamisland.fandom.com/zh/api.php
Getting the XML header from the API
Retrieving the XML for every page from the beginning
30 namespaces found
Trying to export all revisions from namespace 0
Trying to get wikitext from the allrevisions API and to build the XML
Warning. Could not use allrevisions. Wiki too old?
Getting titles to export all the revisions of each
    8號球
9 more revisions exported
    BFB
1 more revisions exported
    BFDI
1 more revisions exported
    BFDIA
1 more revisions exported
    Battle For Dream Island Wiki
1 more revisions exported
    Battle for Dream Island Wiki
13 more revisions exported
    Battle for dream island Wiki
2 more revisions exported
    Chinese Battle For Dream Island Wiki
1 more revisions exported
    Chinese Battle for Dream Island Wiki
2 more revisions exported
    En:
Downloaded 10 pages
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2456, in <module>
    main()
  File "./dumpgenerator.py", line 2448, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 2015, in createNewDump
    generateXMLDump(config=config, titles=titles, session=other['session'])
  File "./dumpgenerator.py", line 723, in generateXMLDump
    for xml in getXMLRevisions(config=config, session=session):
  File "./dumpgenerator.py", line 973, in getXMLRevisions
    raise PageMissingError(title, xml='')
__main__.PageMissingError: page 'En:' not found
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
Also fixed in 7289225d2ccec8f54581fff26cf43462314f5a63 like issue #370. More examples in https://github.com/WikiTeam/wikiteam/issues/362#issuecomment-589951057 . Also reported to Wikia in zendesk report 914330
