### ISSUE TITLE
launcher.py: delete corrupt 7z files

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#366]
Not good to have such stuff lying around:
```
ERROR: ./riordanfandomcom_ru-20200211-history.xml.7z : ./riordanfandomcom_ru-20200211-history.xml.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
```

**Comment by nemobis** [comment]
In any case we need to handle the exception:
```
ERROR: pawpatrolfandomcom-20200213-history.xml.7z : pawpatrolfandomcom-20200213-history.xml.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive

Traceback (most recent call last):
  File "launcher.py", line 126, in <module>
    main()
  File "launcher.py", line 58, in main
    archivecontent = subprocess.check_output (['7za', 'l', zipfilename])
  File "/usr/lib64/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['7za', 'l', 'pawpatrolfandomcom-20200213-history.xml.7z']' returned non-zero exit status 2
```

**Comment by nemobis** [comment]
It also helps if we don't create them in the first place. Don't move the tmp file to 7z unless it's good. Especially relevant when running low on memory:
```

Items to compress: 7

  0% 5 + tinyvillagefandomcom-20200214-history.xml/usr/bin/7za: line 2: 1127942 Killed                  "/usr/libexec/p7zip/7za" "$@"
```

**Comment by nemobis** [comment]
To find them it's enough to do a `7z l`, for instance:
```
$ find -name "*7z" | xargs -I§ -n1 -P128 sh -c "7z l § 2>&1 | grep ^ERROR:" | tee 7z.error.log
```
