### ISSUE TITLE
Dump fails on page "Wikia:About"

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#370]
```
Analysing https://dannyphantomroleplay.fandom.com/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
Resuming XML dump from "Tucker Foley"
https://dannyphantomroleplay.fandom.com/api.php
Getting the XML header from the API
WARNING: will try to start the download from title: Tucker Foley
30 namespaces found
Trying to export all revisions from namespace 0
Trying to get wikitext from the allrevisions API and to build the XML
Warning. Could not use allrevisions. Wiki too old?
Getting titles to export all the revisions of each
    Tucker Foley
        1 more revisions exported
    Wikia:About
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2493, in <module>
    main()
  File "./dumpgenerator.py", line 2483, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 2130, in resumePreviousDump
    session=other['session'])
  File "./dumpgenerator.py", line 727, in generateXMLDump
    for xml in getXMLRevisions(config=config, session=session, start=start):
  File "./dumpgenerator.py", line 977, in getXMLRevisions
    raise PageMissingError(title, xml='')
__main__.PageMissingError: page 'Wikia:About' not found
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

https://dannyphantomroleplay.fandom.com/wiki/Wikia:About redirects to https://www.fandom.com/about

**Comment by nemobis** [comment]
Fixed in 7289225d2ccec8f54581fff26cf43462314f5a63
