### ISSUE TITLE
dumpgenerator.py chokes on a file name

### ISSUE THREAD

**Issue by robkam** [WikiTeam/wikiteam#388]
dumpgenerator.py chokes on the file name [Roland_Aira_TR-8_VS_TR-909_Unbiased_Comparison._HQ*****](https://electronicmusic.fandom.com/wiki/File:Roland_Aira_TR-8_VS_TR-909_Unbiased_Comparison._HQ*****) 

With `python dumpgenerator.py --api=https://electronicmusic.fandom.com/api.php --images`

I get
> Traceback (most recent call last):
>   File "dumpgenerator.py", line 2528, in <module> main()
>   File "dumpgenerator.py", line 2520, in main createNewDump(config=config, other=other)
>   File "dumpgenerator.py", line 2099, in createNewDump session=other['session'])
>   File "dumpgenerator.py", line 1473, in generateImageDump imagefile = open(filename3, 'wb')
> IOError: [Errno 22] invalid mode ('wb') or filename: u'./electronicmusicfandomcom-20200617-wikidump/images/Roland Aira TR-8 VS TR-909 Unbiased Comparison. HQ*****'

**Comment by robkam** [comment]
duplicate of #380
