### ISSUE TITLE
filename encoding

### ISSUE THREAD

**Issue by copslock** [WikiTeam/wikiteam#403]
The script supports ASCII encoding only in filename3 caused the problem,UTF-8 or Unicode will be needed
`Traceback (most recent call last):
  File "dumpgenerator.py", line 2569, in <module>
    main()
  File "dumpgenerator.py", line 2561, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 2140, in createNewDump
    session=other['session'])
  File "dumpgenerator.py", line 1487, in generateImageDump
    imagefile = open(filename3, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-53: ordinal not in range(128)`

**Comment by nemobis** [comment]
Are you sure that's a complete traceback? Please include the URL of the wiki you're dumping.

We know of https://github.com/WikiTeam/wikiteam/issues/269
