### ISSUE TITLE
launcher.py not working

### ISSUE THREAD

**Issue by murolem** [WikiTeam/wikiteam#481]
Hi!

I wanted to download a wiki so a made a `mylist.txt` file and placed `https://cosmoteer.wiki.gg/api.php` inside.

Then I run the script using `python launcher.py mylist.txt` and it just straight up failed:
```bash
Please install the lxml module if you want to use --xmlrevisions.
Reading list of APIs from mylist.txt
1 APIs found
#########################################################################
# Downloading https://cosmoteer.wiki.gg/api.php
#########################################################################
Resuming download, using directory cosmoteerwikigg-20240603-wikidump
Traceback (most recent call last):
  File "launcher.py", line 130, in <module>
    main()
  File "launcher.py", line 85, in main
    subprocess.call(['python2', 'dumpgenerator.py', '--api={}'.format(wiki), '--xml', '--images', '--resume', '--path={}'.format(wikidir)], shell=False)
  File "C:\Users\aliser\.pyenv\pyenv-win\versions\2.7.18\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Users\aliser\.pyenv\pyenv-win\versions\2.7.18\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\aliser\.pyenv\pyenv-win\versions\2.7.18\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
```

I'n on win11, Python 2.7.18. Dependencies are installed with `pip install --upgrade -r requirements.txt`.

**Comment by nemobis** [comment]
Hello, thanks for using WikiTeam. As the message says:

```
Please install the lxml module if you want to use --xmlrevisions.
```

This is an optional requirement hence it's not listed in requirements.txt.
