### ISSUE TITLE
super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by BotJohn** [WikiTeam/wikiteam#485]
When trying to scrape a wiki, I get the following error:
40 namespaces found
    Retrieving titles in the namespace 0
Traceback (most recent call last):
  File "dumpgenerator.py", line 2572, in <module>
    main()
  File "dumpgenerator.py", line 2564, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 2133, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "dumpgenerator.py", line 391, in getPageTitles
    for title in titles:
  File "dumpgenerator.py", line 261, in getPageTitlesAPI
    site = mwclient.Site(apiurl.netloc, apiurl.path.replace("api.php", ""), scheme=apiurl.scheme, pool=session)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 169, in __init__
    self.pages = listing.PageList(self)
  File "C:\Python27\lib\site-packages\mwclient\listing.py", line 242, in __init__
    super(PageList, self).__init__(site, 'allpages', 'ap',
TypeError: super() argument 1 must be type, not classobj

**Comment by nemobis** [comment]
What version of mwclient do you have? How did you install it?

**Comment by BotJohn** [comment]
0.11, installed via pip.

**Comment by Anonymous3-a** [comment]
Same error, any help?

**Comment by Anonymous3-a** [comment]
Ok, try this: run `pip --force-reinstall "mwclient==0.10"`. It's not giving the error now, it seems like it's working?

**Comment by agnelvishal** [comment]
Faced same issue.
The below solved.
` pip install "mwclient==0.10"`

**Comment by TangentFoxy** [comment]
The `--force-reinstall` command just returns an error, but the install command @agnelvishal replied with works.
