### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by birdtoday** [WikiTeam/wikiteam#486]
Hello,

Here, I try to archive Fundamental Paper Education Fandom Wiki with the command `python2.7 dumpgenerator.py https://fundamental-paper-education.fandom.com --xml --images` on Linux debian 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux. We download most images, file names truncate correctly, but it doesn't work here, even after resuming.

`    Downloaded 1680 images
    Downloaded 1690 images
    Downloaded 1700 images
    Downloaded 1710 images
    Downloaded 1720 images
Filename is too long, truncating. Now it is: The Mega Knight is a Legendary card that is unlocked from the Electro Valley (Arena 11). It spawns a660524bc6439aef74e1ea186f6ce7af6.png
    Downloaded 1730 images
    Downloaded 1740 images
    Downloaded 1750 images
    Downloaded 1760 images
    Downloaded 1770 images
    Downloaded 1780 images
    Downloaded 1790 images
    Downloaded 1800 images
    Downloaded 1810 images
    Downloaded 1820 images
    Downloaded 1830 images
    Downloaded 1840 images
    Downloaded 1850 images
    Downloaded 1860 images
    Downloaded 1870 images
    Downloaded 1880 images
    Downloaded 1890 images
    Downloaded 1900 images
    Downloaded 1910 images
    Downloaded 1920 images
    Downloaded 1930 images
    Downloaded 1940 images
    Downloaded 1950 images
    Downloaded 1960 images
    Downloaded 1970 images
    Downloaded 1980 images
    Downloaded 1990 images
    Downloaded 2000 images
    Downloaded 2010 images
    Downloaded 2020 images
    Downloaded 2030 images
    Downloaded 2040 images
    Downloaded 2050 images
    Downloaded 2060 images
    Downloaded 2070 images
    Downloaded 2080 images
    Downloaded 2090 images
    Downloaded 2100 images
    Downloaded 2110 images
Filename is too long, truncating. Now it is: 😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-8eb86b8f32ce7668fd20b6fc80de14eb.😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-2
Traceback (most recent call last):
  File "dumpgenerator.py", line 2572, in <module>
    main()
  File "dumpgenerator.py", line 2564, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 2147, in createNewDump
    session=other['session'])
  File "dumpgenerator.py", line 1494, in generateImageDump
    imagefile = open(filename3, 'wb')
IOError: [Errno 36] File name too long: u'./fundamental_paper_educationfandomcom-20241216-wikidump/images/\U0001f63b\U0001f4ab-\xb0claire?\xb0-\U0001f34e\U0001f381 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-8eb86b8f32ce7668fd20b6fc80de14eb.\U0001f63b\U0001f4ab-\xb0claire?\xb0-\U0001f34e\U0001f381 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-2'
a@debian:~/wikiteam$ python2.7 dumpgenerator.py https://fundamental-paper-education.fandom.com --xml --images --resume --path=fundamental_paper_educationfandomcom-20241216-wikidump/
Checking API... https://fundamental-paper-education.fandom.com/api.php
API is OK: https://fundamental-paper-education.fandom.com/api.php
Checking index.php... https://fundamental-paper-education.fandom.com/index.php
index.php is OK
#########################################################################
# Welcome to DumpGenerator 0.4.0-alpha by WikiTeam (GPL v3)                   #
# More info at: https://github.com/WikiTeam/wikiteam                    #
#########################################################################

#########################################################################
# Copyright (C) 2011-2024 WikiTeam developers                           #

# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

Analysing https://fundamental-paper-education.fandom.com/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
XML dump was completed in the previous session
Image list was completed in the previous session
2115 images were found in the directory from a previous session
Retrieving images from "😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel"
Filename is too long, truncating. Now it is: 😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-8eb86b8f32ce7668fd20b6fc80de14eb.😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-2
Traceback (most recent call last):
  File "dumpgenerator.py", line 2572, in <module>
    main()
  File "dumpgenerator.py", line 2562, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 2283, in resumePreviousDump
    session=other['session'])
  File "dumpgenerator.py", line 1494, in generateImageDump
    imagefile = open(filename3, 'wb')
IOError: [Errno 36] File name too long: u'./fundamental_paper_educationfandomcom-20241216-wikidump/images/\U0001f63b\U0001f4ab-\xb0claire?\xb0-\U0001f34e\U0001f381 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-8eb86b8f32ce7668fd20b6fc80de14eb.\U0001f63b\U0001f4ab-\xb0claire?\xb0-\U0001f34e\U0001f381 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-2'`

Is there a fix for this?

**Comment by nemobis** [comment]
Do I read correctly that we tried to create a literal `😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-8eb86b8f32ce7668fd20b6fc80de14eb.😻💫-°claire?°-🍎🎁 -fundamentalpapereducation -tiktok -nomio -credit -viral -apoyo -zip -oliver -engel-2` file? It would seem that the prefix was repeated instead of the filename extension. What's the extension of the original file?

**Comment by birdtoday** [comment]
[It seems to be a youtube video.](https://fundamental-paper-education.fandom.com/wiki/Fundamental_Paper_Education_Wiki?file=%F0%9F%98%BB%F0%9F%92%AB-%C2%B0claire%3F%C2%B0-%F0%9F%8D%8E%F0%9F%8E%81_-fundamentalpapereducation_-tiktok_-nomio_-credit_-viral_-apoyo_-zip_-oliver_-engel)

**Comment by nemobis** [comment]
Uh. So it has no filename extension because there's no file in the first place, but just a reference to an external resource? How tedious.
