### ISSUE TITLE
Large histories memory error

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#8]
_From [emi...@gmail.com](https://code.google.com/u/109758257449746321618/) on April 16, 2011 23:35:03_

RationalWiki:SPOV 18 edits
RationalWiki:Saloon Bar 1 edits
RationalWiki:Saloon Bar/Drink counter/Archive 1 2 edits
RationalWiki:Saloon bar 2000 edits
RationalWiki:Saloon bar 3000 edits
RationalWiki:Saloon bar 4000 edits
RationalWiki:Saloon bar 5000 edits
RationalWiki:Saloon bar 6000 edits
RationalWiki:Saloon bar 7000 edits
RationalWiki:Saloon bar 8000 edits
RationalWiki:Saloon bar 9000 edits
RationalWiki:Saloon bar 10000 edits
RationalWiki:Saloon bar 11000 edits
RationalWiki:Saloon bar 12000 edits
Traceback (most recent call last):
  File "dumpgenerator.py", line 878, in <module>
    f.close()
  File "dumpgenerator.py", line 785, in main
    xmltitles = re.findall(r'<title>([^<]+)</title>', l) #weird if found more than 1, but maybe
  File "dumpgenerator.py", line 335, in generateXMLDump
    if c &#37; 10 == 0:
  File "dumpgenerator.py", line 279, in getXMLPage
    xml = xml.split('</page>')[0]+xml2.split('<page>\n')[1]
MemoryError

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=8_

**Comment by nemobis** [comment]
I wonder if we have to use something like http://docs.scipy.org/doc/numpy/user/basics.creation.html

Is there some library for  XML which accepts invalid XML files as input and can try to repair them, merge etc.?

**Comment by nemobis** [comment]
Mako suggests, in addition to the use of generators for title listing and revision scanning, to read the XML from the end during resume, also with a generator. https://stackoverflow.com/a/23646049/4145951

The maximum memory consumed will then be whatever it takes to store in memory the largest request we make to Special:Export (which we can reduce by reducing the number of revisions, perhaps in a try except).

**Comment by nemobis** [comment]
Is this a history too big to be downloaded at once, or a bug in https://github.com/WikiTeam/wikiteam/pull/228 ?
```
Removing the last chunk of past XML dump: it is probably incomplete
Cannot allocate memory
Cannot allocate memory
Last 124518 lines removed.
    Creepypasta Wiki:Chat/Logs/8 December 2014, 78 edits
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2005, in <module>
    main()
  File "./dumpgenerator.py", line 1995, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 1649, in resumePreviousDump
    session=other['session'])
  File "./dumpgenerator.py", line 684, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "./dumpgenerator.py", line 612, in getXMLPage
    yield '  <revision>' + ('<revision>'.join(xml2.split('<revision>')[1:]))
MemoryError
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

Either way, one thing I still have to do: a try.. except to catch MemoryError and retry with less revisions.

**Comment by nemobis** [comment]
Mostly fixed with https://github.com/WikiTeam/wikiteam/commit/d4fd745498e55de0f1ae443f5d35af420b9cff13
I *think* we are no longer doing .split() on any huge XML, which was our biggest issue. There are still some places where a MemoryError can occur, perhaps they should be logged by wrapping the entire main() in a try except.

**Comment by nemobis** [comment]
```
  File "./dumpgenerator.py", line 2020, in <module>
    main()
  File "./dumpgenerator.py", line 2010, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 1664, in resumePreviousDump
    session=other['session'])
  File "./dumpgenerator.py", line 687, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "./dumpgenerator.py", line 574, in getXMLPage
    xml = re.sub(r'\n\s*<sha1>\w+</sha1>\s*\n', r'\n', xml)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
And once that's fixed:
```
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2030, in <module>
    main()
  File "./dumpgenerator.py", line 2020, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 1674, in resumePreviousDump
    session=other['session'])
  File "./dumpgenerator.py", line 697, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "./dumpgenerator.py", line 587, in getXMLPage
    yield xml.split("</page>")[0]
MemoryError
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
#########################################################################
```

**Comment by nemobis** [comment]
StringIO is not smart enough :(
```
  File "./dumpgenerator.py", line 2022, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 1676, in resumePreviousDump
    session=other['session'])
  File "./dumpgenerator.py", line 699, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "./dumpgenerator.py", line 582, in getXMLPage
    for line in readxml:
  File "/usr/lib/python2.7/StringIO.py", line 76, in next
    r = self.readline()
  File "/usr/lib/python2.7/StringIO.py", line 164, in readline
    r = self.buf[self.pos:newpos]
MemoryError
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
Funny example works :)
```
Analysing http://glee.wikia.com/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
Resuming XML dump from "Blaine-Kurt Relationship"
Retrieving the XML for every page from "Blaine-Kurt Relationship"
The page's history exceeds our memory, halving limit.
The page's history exceeds our memory, halving limit.
The page's history exceeds our memory, halving limit.
    Blaine-Kurt Relationship, 3483 edits
```

**Comment by nemobis** [comment]
IIRC this still failed some wiki downloads, which I left rotting since then. For now I'll focus on another round of generic/small wikis downloads, avoiding the huge ones (not enough disk space anyway), so I won't be able to test thoroughly.

**Comment by DanielOaks** [comment]
I just had this while trying to download a decently large wiki:

```
Traceback (most recent call last):
  File "./dumpgenerator.py", line 2054, in <module>
    main()
  File "./dumpgenerator.py", line 2046, in main
    createNewDump(config=config, other=other)
  File "./dumpgenerator.py", line 1621, in createNewDump
    generateXMLDump(config=config, titles=titles, session=other['session'])
  File "./dumpgenerator.py", line 695, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "./dumpgenerator.py", line 629, in getXMLPage
    xml2 = xml2.split("</page>")[0]
MemoryError
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

**Comment by nemobis** [comment]
Please also check that all the revisions are actually being downloaded. (One possible method: at the end of the process we have a simple grep which counts the page and revision tags, compare that to the statistics in the wiki.)

**Comment by nemobis** [comment]
The current solution is to use `--xmlrevisions` https://github.com/WikiTeam/wikiteam/issues/311 , I closed https://github.com/WikiTeam/wikiteam/issues/282

**Comment by nemobis** [comment]
A giant page on which this can be tested: https://wiki.thingsandstuff.org/index.php?title=Audio&offset=&limit=5000&action=history . For now the graduated response seems to work:
```
Analysing https://wiki.thingsandstuff.org/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
Resuming XML dump from "Audio"
https://wiki.thingsandstuff.org/api.php
Retrieving the XML for every page from "Audio"
Removing the last chunk of past XML dump: it is probably incomplete.
The page's history exceeds our memory, halving limit.
The page's history exceeds our memory, halving limit.
The page's history exceeds our memory, halving limit.
```
We'll see if it reaches the end.

**Comment by nemobis** [comment]
We have one MemoryError on resume:
```
Analysing http://wiki.urbandead.com/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
Resuming XML dump from "NecroWatch/Procedures"
http://wiki.urbandead.com/api.php
Retrieving the XML for every page from "NecroWatch/Procedures"
Removing the last chunk of past XML dump: it is probably incomplete.
nSleeping... 0 seconds...
    NecroWatch/Procedures, 2 edits
Sleeping... 0 seconds...
Traceback (most recent call last):
  File "dumpgenerator.py", line 2528, in <module>
    main()
  File "dumpgenerator.py", line 2518, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 2165, in resumePreviousDump
    session=other['session'])
  File "dumpgenerator.py", line 764, in generateXMLDump
    for xml in getXMLPage(config=config, title=title, session=session):
  File "dumpgenerator.py", line 616, in getXMLPage
    xml = re.sub(r'\n\s*<sha1>\w+</sha1>\s*\n', r'\n', xml)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError
```
