### ISSUE TITLE
IOError: [Errno 2] on dumpgenerator with image filename containing /

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#86]
_From [joehow...@gmail.com](https://code.google.com/u/105176478744817458663/) on January 27, 2014 21:09:34_

I am using dumpgenerator revision r882 on windows 7 and I am getting the following error:
Traceback (most recent call last):
  File "dumpgenerator.py", line 1220, in <module>
    main()
  File "dumpgenerator.py", line 1211, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 1127, in resumePreviousDump
    generateImageDump(config=config, other=other, images=images, start=lastfilename2) # we resume from previous image, which may be corrupted (or missing .desc)
  by the previous session ctrl-c or abort
  File "dumpgenerator.py", line 673, in generateImageDump
    urllib.urlretrieve(url=url, filename='&#37;s/&#37;s' &#37; (imagepath, filename2) )
  File "C:\Python27\lib\urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 244, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: './norunescapewikiacom-20140127-wikidump/images/Engelsk/Norsk.png'

**Attachment:** [errno2.png](http://code.google.com/p/wikiteam/issues/detail?id=86)

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=86_

**Comment by rsomeon** [comment]
/ is the one character not allowed in filenames on Linux. Has this really been open for over a year now? I ran into this issue today so I made a pull request: https://github.com/WikiTeam/wikiteam/pull/249. Sorry if it overlooks some earlier fix.

**Comment by Slider-Whistle** [comment]
I don't know why this weird bug is still a thing, but you can work around it by cd'ing a directory up and choosing the directory you were just in through the path argument or whatever other things you were using.
