### ISSUE TITLE
uploader.py crashes if archive.org returns 503 error to metadata query

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#99]
_From [nemow...@gmail.com](https://code.google.com/u/101255742639286016490/) on February 04, 2014 11:24:24_

Traceback (most recent call last):
  File "uploader.py", line 300, in <module>
    main()
  File "uploader.py", line 297, in main
    upload(wikis, config)
  File "uploader.py", line 143, in upload
    if urllib2.urlopen(itemdata).read() == '{}':
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Temporarily Unavailable

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=99_

**Comment by nemobis** [comment]
Hmm I've not seen this in a while... Hopefully the internetarchive library takes care of it.
